# FUNCTIONS#

# Assign ability to children given father's wage percentile, mean and sd of ability distribution
c_fcn <- function(w, mean, sd){
  c <- mean + b*(qnorm(w, mean, sd) - mean) + rnorm(1, 0, d)
  return(c)
}

## Calculates mean wage for G2 in first period and second period at each level of education for a given regression
mean_wages <- function(lm, sex){
  output <- data.frame(e = c(0:max(men$educ)), w_0 = NA, w_1 = NA, w_0_s = NA, w_1_s = NA) #make empty dataframe for first and second period wages in both north and south for each level of education
  if(sex == "male"){
    le <- g2_male_life_expectancy - male_marriage_age #second period length
  }
  if(sex == "female"){
    le <- g2_female_life_expectancy - female_marriage_age #second period length
  }
  for(i in 0:max(men$educ)){
    
    current_wage <- lm$coefficients[["(Intercept)"]] + i*lm$coefficients[["educ"]] #first period north wage is intercept of regression + e*beta_e
    
    future_wage <- lm$coefficients[["(Intercept)"]] + i*lm$coefficients[["educ"]] + (sum(c(1:le))/le)*lm$coefficients[["exper"]] + sum(c(1:le)/le)*i*lm$coefficients[["educ_exper"]]  # second period north wage is intercept + e*beta_e + average of second period length years of experience coefficients
    
    current_wage_s <- lm$coefficients[["(Intercept)"]] + i*lm$coefficients[["educ"]]  + lm$coefficients[["south"]] #first period south wage is north wage - coefficient on south dummy
    
    future_wage_s <- lm$coefficients[["(Intercept)"]] + i*lm$coefficients[["educ"]] + (sum(c(1:le))/le)*lm$coefficients[["exper"]] + sum(c(1:le)/le)*i*lm$coefficients[["educ_exper"]] + lm$coefficients[["south"]] + (sum(c(1:le))/le)*lm$coefficients[["exper_south"]] # second period south wage is north second period - south coefficient - average of second period length years of south-experience interaction
    
    output$w_0[i+1] <- current_wage
    output$w_1[i+1] <- future_wage
    output$w_0_s[i+1] <- current_wage_s
    output$w_1_s[i+1] <- future_wage_s
  }
  return(output)
}


## Using dataframe of mean wages generated by mean_wage function, wage_fcn takes level of education and south dummy (1 = south, 0 = non-south) to pull appropriate value from mean wage data frame
wage_fcn <- function(hg, south){
  if(south == 0){ #if north
    cur <- means_lmg2$w_0[which(means_lmg2$e == hg)] #pulls first period wage from dataframe with corresponding level of education
    fut <- means_lmg2$w_1[which(means_lmg2$e == hg)] #pulls second period wage from dataframe with corresponding level of education
    wage <- c(cur, fut)
  }
  if(south == 1){ # if south
    cur <- means_lmg2$w_0_s[which(means_lmg2$e == hg)] #pulls first period (south) wage from dataframe with corresponding level of education
    fut <- means_lmg2$w_1_s[which(means_lmg2$e == hg)] #pulls second period (south) wage from dataframe with corresponding level of education
    wage <- c(cur, fut)
  }
  return(wage)
}

# the same as wage_fcn, but for women. Only outputs first period wage because women are assumed to be homemakers in the second period
wage_fcn_women <- function(hg, south){
  if(south == 0){ #if north
    cur <- means_lmg2_women$w_0[which(means_lmg2_women$e == hg)] #pulls first period wage from dataframe with corresponding level of education
  }
  if(south == 1){ # if south
    cur <- means_lmg2_women$w_0_s[which(means_lmg2_women$e == hg)] #pulls first period (south) wage from dataframe with corresponding level of education
  }
  return(cur)
}

# outputs the male second period wage for a given level of education and south/non-south to be assigned to G2 women in second period as her husband's wage
wife_wage_fcn <- function(hg, south){
  if(south == 1){
    out <- means_lmg2$w_1_s[which(means_lmg2$e == hg)]
  } else {
    out <- means_lmg2$w_1[which(means_lmg2$e == hg)]
  }
  return(out)
}

## For a given G1, calculates utility maximizing level of education for children
educational_attainment_g1 <- function(wage_g1, c, beta, beta_prime, C, s_male,
                                      s_female, south, N, g2_college_men_hours, 
                                      g2_college_women_hours, stipend){
  type <- 0 # type is used to classify G1s into college affordability types. 1 = any children can go to college without stipend, 2 = any children can go to college with stipend, 0 = no children can go
  sons <- sum(rbinom(N, 1, 0.5)) #given number of children, assign sexes with probability 1/2 each is a son
  daughters <- N - sons
  if(sons == N){ # if all children are sons, then automatically chosen to be gender sent to college if affordable
    allocate <- 1
  } else if(sons == 0){ #if all children are daughters, then automatically chosen to be gender sent to college if affordable
    allocate <- 0
  } else {
    allocate <- rbinom(1, 1, p) #choose which gender sent to college if only one can be afforded. 1 = sons, 0 = daughters
  }
  
  second_time <- 0 # second time indicates that if stipend were available, whether all children, only sons, or only daughters would be sent. 1=all, 2 = sons, 3 = daughters
  
  male_college_condition_no_stipend <- 0.25*(1/(N + portion_of_budget_num))*wage_g1 + C - g2_college_men_hours*wage_fcn(12, south)[1] #college affordability condition for sons with no stipend
  female_college_condition_no_stipend <- 0.25*(1/(N + portion_of_budget_num))*wage_g1 + C - g2_college_women_hours*wage_fcn_women(12, south) #college affordability condition for daughters with no stipend
  male_college_condition_stipend <- 0.25*(1/(N + portion_of_budget_num))*wage_g1 + C - g2_college_men_hours*wage_fcn(12, south)[1]- stipend #college affordability condition for sons with stipend
  female_college_condition_stipend <- 0.25*(1/(N + portion_of_budget_num))*wage_g1 + C - g2_college_women_hours*wage_fcn_women(12, south)[1]- stipend #college affordability condition for daughters with stipend
  
  
  
  min_e <- min(ceiling(10*c), 8) #minimum education given by compulsory education laws
  values <- template[which(template$educ_men >= min_e & template$educ_women >= min_e),] # only calculate utility at values above minimum education
  if(wage_g1 >= (portion_of_budget_num + N)*female_college_condition_no_stipend){ # if father can afford college for all children
    values <- values[which(values$educ_men == values$educ_women),]
    type <- 1
  } else if((wage_g1 >= (portion_of_budget_num + sons)*male_college_condition_no_stipend) & 
            (wage_g1 >= (portion_of_budget_num + daughters)*female_college_condition_no_stipend)){ #if either only sons or only daughters can go to college
    type <- 1
    if(allocate == 1){ # if sons go to college
      values <- values[which(values$educ_women <= 12),] #daughters education must be <= 12
      values <- values[which(values$educ_women == pmin(values$educ_men, 12)),] # daughters must graduate high school if sons go to college
    }
    if(allocate == 0){ #if daughters go to college
      values <- values[which(values$educ_men <= 12),] # sons education must be <= 12
      values <- values[which(values$educ_men == pmin(values$educ_women, 12)),] # sons must graduate high school if daughters go to college
    }
  } else if((wage_g1 >= (portion_of_budget_num + sons)*male_college_condition_no_stipend)) { # if only sons can be sent 
    values <- values[which(values$educ_women <= 12),]
    values <- values[which(values$educ_women == pmin(values$educ_men, 12)),]
    type <- 1
  }  else if (wage_g1 >= (portion_of_budget_num + daughters)*female_college_condition_no_stipend) { # if only daughters can be sent
    values <- values[which(values$educ_men <= 12),]
    values <- values[which(values$educ_men == pmin(values$educ_women, 12)),]
    type <- 1
  } else if(wage_g1 >= (portion_of_budget_num + N)*female_college_condition_stipend){ # if all children can be sent if stipend were made available
    values <- values[which(values$educ_men <= 12),]
    values <- values[which(values$educ_men == values$educ_women),]
    type <- 2
    second_time <- 1
  } else if((wage_g1 >= (portion_of_budget_num + sons)*male_college_condition_stipend) & 
            (wage_g1 >= (portion_of_budget_num + daughters)*female_college_condition_stipend)){ #if either only sons or only daughter can be sent if stipends were made available
    type <- 2 
    if(allocate == 1){ #if only sons are sent
      values <- values[which(values$educ_women <= 12),]
      values <- values[which(values$educ_women == values$educ_men),]
      second_time <- 2
    }
    if(allocate == 0){ # if only daughters are sent
      values <- values[which(values$educ_men <= 12),]
      values <- values[which(values$educ_men == values$educ_women),]
      second_time <- 3
    }
  } else if(wage_g1 >= (portion_of_budget_num + sons)*male_college_condition_stipend){ #if only sons can be sent
    values <- values[which(values$educ_women <= 12),]
    values <- values[which(values$educ_women == values$educ_men),]
    type <- 2
    second_time <- 2
  } else if(wage_g1 >= (portion_of_budget_num + daughters)*female_college_condition_stipend){ #if only daughters can be sent
    values <- values[which(values$educ_men <= 12),]
    values <- values[which(values$educ_men == values$educ_women),]
    type <- 2
    second_time <- 3
  } else { # else no children can go to college
    values <- values[which(values$educ_men == values$educ_women),] # all children have same level of education
    values <- values[which(values$educ_men <= 12),] # maximum education is 12
    type <- 0
  }
  
  # assigns appropriate college affordability condition to children for consumption equations
  if(type == 1){
    female_college_condition <- female_college_condition_no_stipend
    male_college_condition <- male_college_condition_no_stipend
  } else if(type == 2){
    female_college_condition <- female_college_condition_stipend
    male_college_condition <- male_college_condition_stipend
  } else {
    female_college_condition <- 0
    male_college_condition <- 0
  }
  male_first_period <- pmax(male_marriage_age - start_school - values$educ_men/c, 0) #length of first period for G2 men
  female_first_period <- pmax(female_marriage_age - start_school - values$educ_women/c, 0) #length of first period for G2 women
  male_second_period <- g2_male_life_expectancy - pmax(male_marriage_age, start_school + values$educ_men/c) #second period length for G2 men
  female_second_period <- g2_female_life_expectancy-diff - pmax(female_marriage_age, start_school + values$educ_women/c) #second period length for G2 women = second period length for G2 men with same level of education
  
  # initializing variables
  wage_1 <- 0
  wage_2 <- 0
  cost_living_male <- 0
  college_male <- 0
  cost_living_female <- 0
  college_female <- 0
  wage_women <- 0
  c0_male <- 0
  c1_male <- 0
  c0_female <- 0
  c1_female <- 0
  
  if(daughters > 0){
    cost_living_female <- (1/(N + portion_of_budget_num))*wage_g1*(start_school + pmin(12, values$educ_women)/c) #cost of living transfer from parents to daughters
    college_female <- (female_college_condition*(pmax(values$educ_women, 12) - 12))/(c) #cost of college to parents
    own_college_female <- (C + 0.25*(1/(N + portion_of_budget_num))*wage_g1)*(pmax(values$educ_women, 12) - 12)/c #consumption while in college for daughters
    wage_women <- t(sapply(values$educ_women, wage_fcn_women, south=south)) #G2 women first period wages
    wife_wages <- sapply(values$educ_women, wife_wage_fcn, south = south) #G2 women second period wages, which are husband's wages
    son_wages <- t(sapply(values$educ_women, wage_fcn, south = south)) # wages of sons (G3s) in G2 women's second periods
    son_wages <- son_wages[,1]
  }
  if(sons > 0){
    wage <- t(sapply(values$educ_men, wage_fcn, south = south)) #get wages using wage_fcn
    wage_1 <- wage[,1] #G2 men first period wages
    wage_2 <- wage[,2] #G2 men second period wages
    cost_living_male <- (1/(N + portion_of_budget_num))*wage_g1*(start_school + pmin(12, values$educ_men)/c) #cost of living transfer while G2 sons in school
    college_male <- (1/c)*(male_college_condition)*(pmax(values$educ_men, 12) - 12) #college cost to parents for sons
    own_college_male <- (C + 0.25*(1/(N + portion_of_budget_num))*wage_g1)*(pmax(values$educ_men, 12) - 12)/c # college consumption for sons
  }
  total_wages_father <- (g2_first_period_hours)*(s_male*sons*wage_1*male_first_period) + 
    g2_first_period_hours_female*s_female*daughters*wage_women*female_first_period #wages remitted from children to parents
  if(daughters > 0){
    c0_female <- cost_living_female + (1 - s_female)*g2_first_period_hours_female*(female_first_period*wage_women) + own_college_female #first period consumption = cost of living transfers before college + college consumption + (wages - remittances after school before marriage)
    c1_female <- (g2_second_period_hours)*female_second_period*wife_wages - 
      (g2_second_period_hours)*g2_kids*(wife_wages/(portion_of_budget_num + g2_kids))*(start_school + (pmin(values$educ_women, 12))/c) + 
      0.5*g2_kids*s_male*(pmax(male_marriage_age-start_school - values$educ_women/c, 0))*son_wages*(g2_first_period_hours) + 
      0.5*g2_kids*s_female*female_first_period*wage_women*(g2_first_period_hours_female) -
      0.5*g2_kids*((pmax(values$educ_women - 12, 0))/c)*(2*wife_wages*g2_second_period_hours/(portion_of_budget_num + g2_kids)*0.25 + 
                                                           male_college_condition + female_college_condition - 
                                                           2*0.25*(1/(N + portion_of_budget_num))*wage_g1) #expected second period consumption = wages earned (husband's) - cost of living transfers to children + wages remitted from children - college costs for children
  }
  if(sons > 0){
    c0_male <- cost_living_male + (1 - s_male)*(g2_first_period_hours)*(male_first_period*wage_1) + own_college_male #first period consumption = cost of living transfers + college consumption + (wages - remittances)
    c1_male <- (g2_second_period_hours)*male_second_period*wage_2 - 
      g2_kids*((g2_second_period_hours)*wage_2/(portion_of_budget_num + g2_kids))*(start_school + (pmin(values$educ_men, 12))/c) + 
      0.5*g2_kids*s_male*male_first_period*wage_1*(g2_first_period_hours) - 
      0.5*g2_kids*((pmax(values$educ_men - 12,0))/c)*(2*wage_2*g2_second_period_hours/(portion_of_budget_num + g2_kids)*0.25 + 
                                                        male_college_condition + female_college_condition - 
                                                        2*0.25*(1/(N + portion_of_budget_num))*wage_g1) + 
      0.5*g2_kids*s_female*(pmax(female_marriage_age - start_school - values$educ_men/c, 0))*sapply(values$educ_men, wage_fcn_women, south = south)*(g2_first_period_hours_female) #expected second period consumption = earnings - cost of living transfers to children + wages remitted from children - college costs
    
  }
  cg1 <- as.vector(g1_period2*wage_g1 - sons*cost_living_male - daughters*cost_living_female + 
                     total_wages_father - sons*college_male - daughters*college_female) #G1 consumption = earnings - cost of living transfers to children + wages remitted from children - college costs
  
  values$utility <- as.vector((cg1^(1 - x))/(1 - x) + (sons/N)*((((c0_male)^(1 - x))/(1 - x)) + beta*(beta_prime)*(((c1_male)^(1 - x))/(1 - x))) + 
                                (daughters/N)*((((c0_female)^(1 - x))/(1 - x)) + beta*(beta_prime)*(((c1_female)^(1 - x))/(1 - x))))
  
  # output dataframe with utility maximizing educational investments, number of sons and daughters, college affordability type, and second_time (if type = 2, which children would attend college if stipend available)
  if(length(which(is.na(values$utility) == TRUE)) != nrow(values)){
    edu <- values[which(values$utility == max(values$utility,na.rm=TRUE)), 1:2]
    edu <- edu[1,]
  } else {
    edu <- data.frame(educ_men = 0, educ_women = 0)
  }
  edu$sons <- sons
  edu$daughters <- N - sons
  edu$type <- type
  out <- edu
  out$second_time <- second_time
  
  return(out)
}

#this is identical to the previous function, except it is for type 2 households whose children all graduate high school because this is the population who would be applying for stipends
educational_attainment_stipend <- function(wage_g1, c, beta, beta_prime, C, s_male, s_female, south, sons, daughters, 
                                           second_time, g2_college_men_hours, g2_college_women_hours, stipend){
  N <- sons + daughters
  male_college_condition <- 0.25*(1/(N + portion_of_budget_num))*wage_g1 + C - g2_college_men_hours*wage_fcn(12, south)[1]- stipend
  female_college_condition <- 0.25*(1/(N + portion_of_budget_num))*wage_g1 + C - g2_college_women_hours*wage_fcn_women(12, south)[1]- stipend
  
  min_e <- 12
  
  values <- template[which(template$educ_men >= min_e & template$educ_women >= min_e),]
  if(second_time == 1){
    values <- values[which(values$educ_men == values$educ_women),]
  } else if(second_time == 2) {
    values <- values[which(values$educ_women <= 12),]
  } else if(second_time == 3) {
    values <- values[which(values$educ_men <= 12),]
  }
  
  male_first_period <- pmax(male_marriage_age - start_school - values$educ_men/c, 0)
  female_first_period <- pmax(female_marriage_age - start_school - values$educ_women/c, 0)
  male_second_period <- g2_male_life_expectancy - pmax(male_marriage_age, start_school + values$educ_men/c)
  female_second_period <- g2_female_life_expectancy - diff - pmax(female_marriage_age, start_school + values$educ_women/c)
  
  wage_1 <- 0
  wage_2 <- 0
  cost_living_male <- 0
  college_male <- 0
  cost_living_female <- 0
  college_female <- 0
  wage_women <- 0
  c0_male <- 0
  c1_male <- 0
  c0_female <- 0
  c1_female <- 0
  
  if(daughters > 0){
    cost_living_female <- (1/(N + portion_of_budget_num))*wage_g1*(start_school + pmin(12, values$educ_women)/c)
    college_female <- (female_college_condition*(pmax(values$educ_women, 12) - 12))/(c)
    own_college_female <- (C + 0.25*(1/(N + portion_of_budget_num))*wage_g1)*(pmax(values$educ_women, 12) - 12)/c
    wage_women <- t(sapply(values$educ_women, wage_fcn_women, south = south))
    wife_wages <- sapply(values$educ_women, wife_wage_fcn, south = south)
    son_wages <- t(sapply(values$educ_women, wage_fcn, south = south))
    son_wages <- son_wages[,1]
  }
  if(sons > 0){
    wage <- t(sapply(values$educ_men, wage_fcn, south = south))
    wage_1 <- wage[,1]
    wage_2 <- wage[,2]
    cost_living_male <- (1/(N + portion_of_budget_num))*wage_g1*(start_school + pmin(12, values$educ_men)/c)
    college_male <- (1/c)*(male_college_condition)*(pmax(values$educ_men, 12) - 12)
    own_college_male <- (C + 0.25*(1/(N + portion_of_budget_num))*wage_g1)*(pmax(values$educ_men, 12) - 12)/c
  }
  total_wages_father <- (g2_first_period_hours)*(s_male*sons*wage_1*male_first_period) + 
    g2_first_period_hours_female*s_female*daughters*wage_women*female_first_period
  
  if(daughters > 0){
    c0_female <- cost_living_female + (1 - s_female)*g2_first_period_hours_female*(female_first_period*wage_women) + own_college_female
    c1_female <- (g2_second_period_hours)*female_second_period*wife_wages - 
      (g2_second_period_hours)*g2_kids*(wife_wages/(portion_of_budget_num + g2_kids))*(start_school + (pmin(values$educ_women, 12))/c) + 
      0.5*g2_kids*s_male*(pmax(male_marriage_age - start_school - values$educ_women/c, 0))*son_wages*(g2_first_period_hours) + 
      0.5*g2_kids*s_female*female_first_period*wage_women*(g2_first_period_hours_female) - 
      0.5*g2_kids*((pmax(values$educ_women - 12, 0))/c)*(2*wife_wages*g2_second_period_hours/(portion_of_budget_num + g2_kids)*0.25 +
                                                           male_college_condition + female_college_condition - 
                                                           2*0.25*(1/(N + portion_of_budget_num))*wage_g1)
  }
  if(sons > 0){
    c0_male <- cost_living_male + (1 - s_male)*(g2_first_period_hours)*(male_first_period*wage_1) + own_college_male
    c1_male <- (g2_second_period_hours)*male_second_period*wage_2 - 
      g2_kids*((g2_second_period_hours)*wage_2/(portion_of_budget_num + g2_kids))*(start_school + (pmin(values$educ_men, 12))/c) +
      0.5*g2_kids*s_male*male_first_period*wage_1*(g2_first_period_hours) -
      0.5*g2_kids*((pmax(values$educ_men-12,0))/c)*(2*wage_2*g2_second_period_hours/(portion_of_budget_num + g2_kids)*0.25 +
                                                      male_college_condition + female_college_condition - 
                                                      2*0.25*(1/(N + portion_of_budget_num))*wage_g1) + 
      0.5*g2_kids*s_female*(pmax(female_marriage_age - start_school - values$educ_men/c, 0))*sapply(values$educ_men, wage_fcn_women, south = south)*(g2_first_period_hours_female)
    
  }
  cg1 <- as.vector(g1_period2*wage_g1 - sons*cost_living_male - daughters*cost_living_female + 
                     total_wages_father - sons*college_male - daughters*college_female)
  
  values$utility <- as.vector((cg1^(1 - x))/(1 - x) + (sons/N)*((((c0_male)^(1 - x))/(1  -x)) + beta*(beta_prime)*(((c1_male)^(1-x))/(1-x))) + 
                                (daughters/N)*((((c0_female)^(1 - x))/(1 - x))+beta*(beta_prime)*(((c1_female)^(1  -x))/(1 - x))))
  if(length(which(is.na(values$utility) == TRUE)) != nrow(values)){
    edu <- values[which(values$utility == max(values$utility, na.rm=TRUE)), 1:2]
    edu <- edu[1,]
  } else {
    edu <- data.frame(educ_men = 0, educ_women = 0)
  }
  out <- edu
  return(out)
}
